plugins {
    id 'com.android.application'
}

android {
    namespace 'com.redterracestudio.emberascent'
    compileSdk 36

    defaultConfig {
        applicationId "com.redterracestudio.emberascent"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "0.1"
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
